/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ShabtiEngine {
  constructor(config: NapiEngineConfig)
  store(content: string, options?: NapiStoreOptions | undefined | null): Promise<NapiStoreResult>
  search(query: string, limit?: number | undefined | null): Promise<Array<NapiSearchResult>>
  executeQuery(query: NapiQuery): Promise<Array<NapiQueryResult>>
  get(id: string): Promise<NapiSearchResult>
  delete(id: string): Promise<void>
  snapshotCreate(): NapiSnapshot
  snapshotRestore(id: string): void
  snapshotList(): Array<NapiSnapshot>
  modelId(): string
  status(): NapiStatus
  listEntries(options?: NapiListOptions | undefined | null): Array<NapiExportEntry>
  gc(): Promise<number>
  shutdown(): Promise<void>
  graphInfo(): NapiGraphInfo
}
export type ShabtiNapi = ShabtiEngine

/**
 * Detect contradiction between two text strings.
 * Returns whether a contradiction was found and its type (NumericDifference or NegationDifference).
 */
export declare function detectContradictionNapi(textA: string, textB: string): NapiContradictionResult

export interface NapiContradictionResult {
  detected: boolean
  contradictionType?: string
}

export interface NapiEngineConfig {
  qdrantUrl: string
  collectionName?: string
  dataDir: string
}

export interface NapiExplanation {
  semanticSimilarity: number
  timeDecayFactor: number
  accessBoostFactor: number
  matchedAtLevel: number
  linkHops: number
  isSuperseded: boolean
  dedupeCount: number
  finalScore: number
}

export interface NapiExportEntry {
  id: string
  content: string
  namespace: string
  tags: Array<string>
  keywords: Array<string>
  sessionId: string
  createdAt: number
  expiresAt?: number
  lifecycleState: string
  originType: string
  modelId: string
  embedding?: Array<number>
  metadata?: string
}

export interface NapiGraphInfo {
  nodeCount: number
  edgeCount: number
}

export interface NapiListOptions {
  namespace?: string
  limit?: number
  includeEmbeddings?: boolean
}

export interface NapiQuery {
  text: string
  limit?: number
  namespace?: string
  timeStart?: number
  timeEnd?: number
  clusterId?: number
  maxHops?: number
  minScore?: number
  excludeSuperseded?: boolean
  withExplanation?: boolean
}

export interface NapiQueryResult {
  id: string
  content: string
  score: number
  namespace: string
  createdAt: number
  expiresAt?: number
  explanation?: NapiExplanation
}

export interface NapiSearchResult {
  id: string
  content: string
  score: number
  namespace: string
  createdAt: number
  expiresAt?: number
}

export interface NapiSnapshot {
  id: string
  createdAt: number
}

export interface NapiStatus {
  entryCount: number
  tier: string
  qdrantUrl: string
  dataDir: string
  modelId: string
}

export interface NapiStoreOptions {
  namespace?: string
  sessionId?: string
  tags?: Array<string>
  ttlSeconds?: number
}

export interface NapiStoreResult {
  status: string
  id?: string
  existingId?: string
}
