pub mod a2a;
pub mod agent;
pub mod benchmark;
pub mod clustering;
pub mod contradiction;
pub mod dedup;
pub mod entry;
pub mod error;
pub mod event;
pub mod gate;
pub mod health;
pub mod mcp;
pub mod metrics;
pub mod namespace;
pub mod near_dedup;
pub mod orchestrator;
pub mod procedural;
pub mod query;
pub mod resolution;
pub mod scoring;
pub mod sharing;
pub mod traits;
pub mod types;

pub use dedup::DedupChecker;
pub use entry::{MemoryEntry, MemoryEntryBuilder};
pub use error::{ShabtiError, ShabtiResult};
pub use event::Event;
pub use gate::{DataTier, FeatureGate};
pub use types::{LifecycleState, OriginType};
